### PR TITLE
Kraken2 unique k-mer counting

### PR DESCRIPTION
**Pull request by martin-steinegger**
Integration of Florian Breitwieser's (@fbreitwieser) KrakenUniq hyperloglog k-mer counting code [1] into Kraken2. This change adds two extra fields, (1) k-mer count and (2) unique k-mer, to the Kraken report. 

```
1. Percentage of reads at this taxon
2. Number of reads at this taxon
3. Number of reads assigned directly to this taxon
4. k-mer count at this taxon
5. Unique k-mer at this taxon
6. A rank code
7. NCBI taxonomic ID number
8. Indented scientific name
```

Old report:
```
 99.65	409253	409253	U	0	unclassified
  0.35	1443	0	R	1	root
  0.35	1443	0	D	10239	  Viruses
  0.13	535	0	D1	2559587	    Riboviria
  0.08	331	0	F	11050	      Flaviviridae
  0.08	331	7	G	11051	        Flavivirus
  0.07	302	302	S	11083	          Powassan virus
  0.00	14	14	S	11086	          Louping ill virus
```
New Report: 

```
99.65	409253	0	0	0	U	0	unclassified
0.3514	1443	0	25002	6638	R	1	root
0.3514	1443	0	25002	6638	D	10239	  Viruses
0.1303	535	0	3900	494	D1	2559587	    Riboviria
0.08059	331	0	2629	366	F	11050	      Flaviviridae
0.08059	331	7	2629	366	G	11051	        Flavivirus
0.07353	302	302	2377	329	S	11083	          Powassan virus
0.003409	14	14	36	6	S	11086	          Louping ill 
```

### Implementation
I have added the hyperloglog (`readcounts`) counter to `classify.cc` and replaced the kraken report code (function `ReportKrakenStyle`) with my class `TaxReport`. 

Files added + (License): 
`GPLv3`: `hyperloglogplus.cc` `hyperloglogplus.h` `hyperloglogplus-bias.h` `readcounts.h` 
`MIT`: `khash.h` 
`AGPLv3`: `khset.h` 

### References

[1] [KrakenUniq: confident and fast metagenomics classification using unique k-mer counts. Breitwieser FP, Baker DN, Salzberg SL. Genome Biology, Dec 2018. https://doi.org/10.1186/s13059-018-1568-0](https://doi.org/10.1186/s13059-018-1568-0)

### CODE REVIEW

**Comment by martin-steinegger** [comment]
@DerrickWood the license clash should be resolved thanks to @dnbaker and @fbreitwieser (https://github.com/fbreitwieser/krakenuniq/blob/master/README.md#license). Thank you so much!

**Comment by maxibor** [comment]
Hi @martin-steinegger and @DerrickWood , and thanks for the amazing work 😃 
Is there any update on this PR ? Would love to see KrakenUniq in Kraken2 😍

**Comment by martin-steinegger** [comment]
@maxibor Thank you. @BenLangmead cleaned the the code and opened a different PR https://github.com/DerrickWood/kraken2/pull/249, which is already merged into kraken2. You should be able to see unique counts in the kraken report. :)

**Comment by maxibor** [comment]
Wonderful ! Thanks @martin-steinegger !

**Comment by NikolayOskolkov** [comment]
Dear @martin-steinegger and @DerrickWood,
thanks a lot for your great tool! I can see from this thread that unique kmer counts should be available now in Kraken2. Could you please let me know how I can install the version of Kraken2 with unique kmer counts implemented? So far I did not succeed to get it produce unique kmers so I assume I am still installing a wrong / old version. Would appreciate your help, thanks!

**Pull request closed without merging**
