### PR TITLE
add bioconda and Galaxy badge

### PR DESCRIPTION
**Pull request by bgruening**
This is adding a Bioconda and a Galaxy badge.

At the time of writing `kraken2` was downloaded 11k times from Bioconda and executed 11221 times on the European Galaxy server.

### CODE REVIEW

**Comment by jenniferlu717** [comment]
The reason we have not done this previously is that we (as in the main Kraken 2 authors/those maintaining the code) are not also maintaining/guaranteeing the bioconda/galaxy versions/compatibility. 

This may change in the future if we can dedicate 100% of our time to maintaining the code but at present, we cannot.

**Comment by bgruening** [comment]
@jenniferlu717 no one is expecting you to do this I think. This would be a lot of work and a huge burden. The community is big and you can not maintain all packages in debian/brew/conda and others. Pointing people to those resources is imho fine as long as you trust those communities. 11k downloads are not bad I would say :)

**Comment by BenLangmead** [comment]
@DerrickWood This is a good idea and I suggest we merge soon

**Comment by bgruening** [comment]
Thanks @BenLangmead and @DerrickWood!

**Pull request merged**
