### PR TITLE
Kraken2 unique k-mer counting, more minimal PR

### PR DESCRIPTION
**Pull request by BenLangmead**
This is a new pull request based on @martin-steinegger port of @fbreitwieser's code.  I trimmed it back to be the minimal pull request that worked for me, built against the current head of master branch in DerrickWood/kraken2.  I trimmed away (a) some needless whitespace changes, (b) an unrelated change to the Makefile, (c) the addition of the khash and kset headers which are not currently usable as far as I can tell.

I also added a couple small things.  I added a `-N` option that causes the output to revert to the original Kraken style report, without the extra columns.  I also ported a more complete set of `#define`s from @fbreitwieser's code giving the full range of exact-counting options.

I don't think either of the two exact-counting options (khset and unordered_set) will work without further changes.  But seemed helpful to the ifdefs for them for when (/if) we do want to bring back exact counting, which would presumably only be for debugging purposes.

### CODE REVIEW

**Comment by ktmeaton** [comment]
Thank you for implementing unique kmer counting! I wanted to test out this pull request and observed 2 results that I can't figure out.

1. More reads classified than reads inputted. >100% classified for some taxa (ex. Bacteria)
2. The minimum reads assigned to a taxa is never below 3.

**Input Data**: The chromosome of the bacteria [Yersinia pestis](https://www.ncbi.nlm.nih.gov/nuccore/NC_003143.1), shredded into 100,000 reads 35-180bp.
**Database**: Tested on the [kraken2-microbial database](https://lomanlab.github.io/mockcommunity/mc_databases.html).
**Command**:
```
kraken2 \
  --db /path/to/kraken2-microbial-fatfree/ \
  --threads 10 \
  --output sample_reads.output \
  --confidence 0.2 \
  --report sample_reads.report \
  --minimum-hit-groups 2 \
  sample_reads.fasta
```

### 2.0.9beta + PR#249

```
4.472   4472    0       0       0       U       0       unclassified
111     111011  3       5270572 1629696 R       1       root
111     111008  8       5269888 1628839 R1      131567    cellular organisms
111     111000  127     5268420 1628411 D       2           Bacteria
110.9   110873  2677    5251627 1625022 P       1224          Proteobacteria
108.2   108193  251     5108663 1618291 C       1236            Gammaproteobacteria
107.9   107939  2449    5070181 1608315 O       91347             Enterobacterales
105.5   105490  224     4846168 1545193 F       1903411             Yersiniaceae
105.3   105266  2513    4813347 1539220 G       629                   Yersinia
102.7   102746  92997   4540349 1456730 G1      1649845                 Yersinia pseudotuberculosis complex
9.633   9633    9573    280238  91338   S       632                       Yersinia pestis
0.029   29      29      755     261     S1      214092                      Yersinia pestis CO92
0.012   12      12      534     196     S1      349746                      Yersinia pestis Angola
0.003   3       3       159     57      S1      637385                      Yersinia pestis D182038
0.003   3       3       132     50      S1      360102                      Yersinia pestis Antiqua
0.003   3       0       117     44      S1      385964                      Yersinia pestis subsp. pestis
0.003   3       0       117     44      S2      1234662                       Yersinia pestis subsp. pestis bv. Medievalis
0.003   3       3       117     44      S3      547048                          Yersinia pestis biovar Medievalis str. Harbin 35
0.003   3       3       105     35      S1      187410                      Yersinia pestis KIM10+
0.003   3       3       63      12      S1      386656                      Yersinia pestis Pestoides F
0.002   2       2       64      22      S1      1345706                     Yersinia pestis 3067
0.002   2       2       26      13      S1      748678                      Yersinia pestis str. Pestoides B
0.096   96      65      3122    1008    S       633                       Yersinia pseudotuberculosis
0.021   21      21      611     203     S1      502800                      Yersinia pseudotuberculosis YPIII
0.008   8       0       224     77      S1      109458                      Yersinia pseudotuberculosis (type O:1b)
0.008   8       8       224     77      S2      748672                        Yersinia pseudotuberculosis str. PA3606
0.002   2       2       14      7       S1      502801                      Yersinia pseudotuberculosis PB1/+
0.02    20      20      1099    376     S       367190                    Yersinia similis
0.004   4       4       148     36      S       29484                   Yersinia frederiksenii
0.003   3       0       66      25      S       29483                   Yersinia aldovae
0.003   3       3       66      25      S1      1453495                   Yersinia aldovae 670-83
0.003   3       0       40      11      O       135623            Vibrionales
0.003   3       0       40      11      F       641                 Vibrionaceae
0.003   3       0       40      11      G       662                   Vibrio
0.003   3       0       22      8       G1      717610                  Vibrio harveyi group
0.003   3       3       18      6       S       680                       Vibrio campbellii
0.003   3       0       108     10      C       28211           Alphaproteobacteria
0.003   3       0       108     10      O       204457            Sphingomonadales
0.003   3       0       108     10      F       335929              Erythrobacteraceae
0.003   3       0       108     10      G       361177                Altererythrobacter
0.003   3       3       108     10      S       2185142                 Altererythrobacter sp. ZODW24
```

### 2.0.9beta (conda recipe)
```
  4.47  4472    4472    U       0       unclassified
 95.53  95528   1       R       1       root
 95.53  95527   4       R1      131567    cellular organisms
 95.52  95523   110     D       2           Bacteria
 95.41  95413   2209    P       1224          Proteobacteria
 93.20  93203   228     C       1236            Gammaproteobacteria
 92.97  92974   2110    O       91347             Enterobacterales
 90.86  90863   215     F       1903411             Yersiniaceae
 90.65  90648   2180    G       629                   Yersinia
 88.46  88464   80043   G1      1649845                 Yersinia pseudotuberculosis complex
  8.30  8299    8245    S       632                       Yersinia pestis
  0.03  29      29      S1      214092                      Yersinia pestis CO92
  0.01  10      10      S1      349746                      Yersinia pestis Angola
  0.00  3       3       S1      360102                      Yersinia pestis Antiqua
  0.00  3       0       S1      385964                      Yersinia pestis subsp. pestis
  0.00  3       0       S2      1234662                       Yersinia pestis subsp. pestis bv. Medievalis
  0.00  3       3       S3      547048                          Yersinia pestis biovar Medievalis str. Harbin 35
  0.00  2       2       S1      748678                      Yersinia pestis str. Pestoides B
  0.00  2       2       S1      187410                      Yersinia pestis KIM10+
  0.00  1       1       S1      1345710                     Yersinia pestis 1045
  0.00  1       1       S1      637385                      Yersinia pestis D182038
  0.00  1       1       S1      377628                      Yersinia pestis Nepal516
  0.00  1       1       S1      1345706                     Yersinia pestis 3067
  0.00  1       1       S1      386656                      Yersinia pestis Pestoides F
  0.10  95      71      S       633                       Yersinia pseudotuberculosis
  0.01  15      15      S1      502800                      Yersinia pseudotuberculosis YPIII
  0.01  6       0       S1      109458                      Yersinia pseudotuberculosis (type O:1b)
  0.01  6       6       S2      748672                        Yersinia pseudotuberculosis str. PA3606
  0.00  1       1       S1      273123                      Yersinia pseudotuberculosis IP 32953
  0.00  1       1       S1      349747                      Yersinia pseudotuberculosis IP 31758
  0.00  1       1       S1      502801                      Yersinia pseudotuberculosis PB1/+
  0.03  27      27      S       367190                    Yersinia similis
  0.00  2       0       S       29483                   Yersinia aldovae
  0.00  2       2       S1      1453495                   Yersinia aldovae 670-83
  0.00  2       2       S       29484                   Yersinia frederiksenii
  0.00  1       1       F       543                 Enterobacteriaceae
  0.00  1       0       O       135623            Vibrionales
  0.00  1       0       F       641                 Vibrionaceae
  0.00  1       0       G       662                   Vibrio
  0.00  1       0       G1      717610                  Vibrio harveyi group
  0.00  1       1       S       680                       Vibrio campbellii
  0.00  1       0       C       28211           Alphaproteobacteria
  0.00  1       0       O       204457            Sphingomonadales
  0.00  1       0       F       335929              Erythrobacteraceae
  0.00  1       0       G       361177                Altererythrobacter
  0.00  1       1       S       2185142                 Altererythrobacter sp. ZODW24
```

I'm not sure if this is a problem with my usage, or the PR changes itself. Any suggestions would be helpful, thanks for implementing this feature!

**Comment by ktmeaton** [comment]
Perhaps I've started to isolate the problem? The min reads >= 3 observation wasn't reproducible. But instead, the output is consistently "correct", while the report file changes every time I run the code in this PR. For example, tracking the taxid #629.

### kraken2 2.0.9beta

```
$ grep -w 629 latest.report
 90.65  90648   2180    G       629    Yersinia
```

```bash
$ cut -f 3 latest.output | grep -w -c 629
2180
```
Report and output agrees, 2180 reads classified exactly at this node.

### kmeruniq Run 1

```
$ grep -w 629 kmeruniq.report
105.2	105176  2507  4789195  1526382  G  629	Yersinia
```

```bash
$ cut -f 3 kmeruniq.output | grep -w -c 629
2180
```
Report and output disagree, 2507 vs. 2180 reads classified.

### kmeruniq Run 2

```
$ grep -w 629 kmeruniq.report
105.3   105266  2513  4813347  1539220  G  629	Yersinia
```

```bash
$ cut -f 3 kmeruniq.output | grep -w -c 629
2180
```
Report and output disagree, 2513 vs 2180 reads classified.

### kmeruniq Run 3

```
$ grep -w 629 kmeruniq.report
105.2  105163  2559  4811840  2498808  G  629	Yersinia
```

```bash
$ cut -f 3 kmeruniq.output | grep -w -c 629
2180
```

Report and output disagree, 2559 vs 2180 reads classified.

**Comment by BenLangmead** [comment]
Thank you for this report!  @martin-steinegger has identified the problem and fixed it in his PR.  I ported his fix over to this more minimal PR as well. Does this fix it for you now, @ktmeaton ?

**Comment by ktmeaton** [comment]
Amazing, thank you so much @martin-steinegger and @BenLangmead for the response and quick fix! The latest commit (e23bdf1) fixed all the issues I described above.

1. Read and kmer counts across sequential runs are now identical.
2. Classification counts are identical between the output file and report file.
3. The calculated kmer coverage (uniq / total) seems appropriate for the test coverage.

Thank you! Looking forward to experimenting with some sample data now.

**Comment by NikolayOskolkov** [comment]
Dear developers of Kraken2,
thanks a lot for your great tool! I can see from this thread that unique kmer counts should be available now in Kraken2. Could you please let me know how I can install the version of Kraken2 with unique kmer counts implemented? So far I did not succeed to get it produce unique kmers so I assume I am still installing a wrong / old version. Would appreciate your help, thanks!

**Pull request merged**
